# shellcheck shell=bash
# -----------------------------------------------------------------------------
# contest-env :: firewall.sh
# Per-user, default-deny egress firewall (nftables, table "inet contest_env").
#
# For packets created by the contest user's processes:
#   * DNS (tcp/udp 53, 853) is rejected, even on loopback. The user has no
#     name resolution at all; the local proxy resolves names on their behalf.
#   * Everything else on loopback is allowed (proxy on 127.0.0.1, local
#     test servers, the IDE's debugger, ...).
#   * Raw IP entries from the allowlist (e.g. an on-site DOMjudge server)
#     are reachable directly.
#   * Everything else is rejected and rate-limit logged.
# Other users (admin, system services, the proxy itself) are not affected.
# -----------------------------------------------------------------------------

# Render the ruleset for USER to stdout.
cm_fw_render() {
  local user="$1" uid v4 v6
  uid="$(id -u "$user")"
  v4="$(cm_expand_whitelist | awk '$1=="ipv4"{print $2}' | paste -sd, -)"
  v6="$(cm_expand_whitelist | awk '$1=="ipv6"{print $2}' | paste -sd, -)"

  cat <<EOF
# Generated by contest-env ($(date '+%F %T')) for user '$user' (uid $uid).
# Do not edit: regenerate with 'sudo cmanager restrict' or 'sudo cmanager reload'.
table inet $CM_NFT_TABLE
delete table inet $CM_NFT_TABLE

table inet $CM_NFT_TABLE {
  set direct_v4 {
    type ipv4_addr; flags interval;
EOF
  [[ -n "$v4" ]] && echo "    elements = { $v4 }"
  cat <<EOF
  }
  set direct_v6 {
    type ipv6_addr; flags interval;
EOF
  [[ -n "$v6" ]] && echo "    elements = { $v6 }"
  cat <<EOF
  }

  chain output {
    type filter hook output priority filter; policy accept;
    meta skuid $uid jump contestant
  }

  chain contestant {
EOF
  if [[ "${DENY_DNS:-1}" == 1 ]]; then
    cat <<'EOF'
    tcp dport { 53, 853 } counter reject with tcp reset comment "no DNS for contestant"
    udp dport { 53, 853 } counter reject comment "no DNS for contestant"
EOF
  fi
  cat <<'EOF'
    oifname "lo" accept comment "loopback (local proxy, local servers)"
    ip daddr @direct_v4 accept comment "allowlisted IPs (e.g. on-site judge)"
    ip6 daddr @direct_v6 accept comment "allowlisted IPs (e.g. on-site judge)"
    limit rate 10/minute burst 20 packets log prefix "contest-env-deny: " level info
    counter reject with icmpx admin-prohibited
  }
}
EOF
}

cm_fw_apply() {
  local user="$1" tmp
  cm_have nft || cm_die "nftables (nft) is not installed — run 'sudo cmanager setup' first"
  mkdir -p "$CM_STATE_DIR"
  tmp="$(mktemp)"
  cm_fw_render "$user" > "$tmp"
  nft -c -f "$tmp" || { rm -f "$tmp"; cm_die "Generated firewall ruleset failed validation"; }
  install -m 0600 "$tmp" "$CM_NFT_FILE"
  rm -f "$tmp"
  nft -f "$CM_NFT_FILE"
  cm_ok "Firewall active: '$user' may only reach loopback (proxy) + allowlisted IPs"
}

cm_fw_remove() {
  nft delete table inet "$CM_NFT_TABLE" 2>/dev/null || true
  rm -f "$CM_NFT_FILE"
}

cm_fw_active() { nft list table inet "$CM_NFT_TABLE" >/dev/null 2>&1; }

# Make sure the table is loaded (used by the guard timer).
cm_fw_ensure() {
  if ! cm_fw_active && [[ -r "$CM_NFT_FILE" ]]; then
    nft -f "$CM_NFT_FILE" && cm_warn "Firewall table was missing — reloaded"
  fi
}
