# shellcheck shell=bash
# -----------------------------------------------------------------------------
# contest-env :: proxy.sh
# Local allowlist proxy (Squid) on 127.0.0.1:$PROXY_PORT.
#
# The contest user can reach the Internet ONLY through this proxy (the
# firewall enforces that). The proxy decides by *domain name*, never by IP,
# so shared CDN addresses (Cloudflare, Google, AWS...) cannot be abused.
#
# HTTPS is never decrypted. When Squid is built with OpenSSL, it "peeks" at
# the TLS ClientHello and checks the SNI server name as well as the CONNECT
# host, so a client cannot CONNECT to an allowed host and then speak TLS to a
# forbidden one (SNI domain fronting). Everything else is spliced untouched.
# -----------------------------------------------------------------------------

CM_SQUID_DIR="$CM_STATE_DIR/squid"
CM_SQUID_CONF="$CM_SQUID_DIR/squid.conf"
CM_PROXY_LOG_DIR="$CM_LOG_DIR/proxy"
CM_PROXY_ACCESS_LOG="$CM_PROXY_LOG_DIR/access.log"
CM_PROXY_UNIT="contest-proxy.service"

cm_squid_bin() {
  local b
  for b in /usr/sbin/squid /usr/local/sbin/squid; do [[ -x "$b" ]] && { echo "$b"; return 0; }; done
  return 1
}

cm_squid_has_openssl() {
  local sq; sq="$(cm_squid_bin)" || return 1
  "$sq" -v 2>/dev/null | grep -q -- '--with-openssl'
}

# Decide whether SNI enforcement is on (SNI_ENFORCE=auto|yes|no).
cm_proxy_sni_enabled() {
  case "${SNI_ENFORCE:-auto}" in
    no|0|false) return 1 ;;
    yes|1|true)
      cm_squid_has_openssl || cm_die "SNI_ENFORCE=yes but Squid lacks OpenSSL (install 'squid-openssl')"
      return 0 ;;
    *) cm_squid_has_openssl ;;
  esac
}

# Write the ACL files + squid.conf into $CM_SQUID_DIR.
cm_proxy_render() {
  local sni=0 proxy_group dom_count ip_count
  cm_proxy_sni_enabled && sni=1
  proxy_group="$(id -gn proxy 2>/dev/null || echo proxy)"

  mkdir -p "$CM_SQUID_DIR" "$CM_PROXY_LOG_DIR"
  chown root:"$proxy_group" "$CM_SQUID_DIR"; chmod 0750 "$CM_SQUID_DIR"
  chown proxy:"$proxy_group" "$CM_PROXY_LOG_DIR" 2>/dev/null || true
  chmod 0750 "$CM_PROXY_LOG_DIR"

  # Domain allowlist: ".example.com" matches example.com and all sub-domains.
  cm_expand_whitelist | awk '$1=="domain"{print $2}' | cm_collapse_domains \
    | sed 's/^/./' | cm_write_file "$CM_SQUID_DIR/allow-domains.acl" 0640
  cm_expand_whitelist | awk '$1=="ipv4"||$1=="ipv6"{print $2}' \
    | cm_write_file "$CM_SQUID_DIR/allow-ips.acl" 0640
  cm_read_list_merged "$CM_AI_DENYLIST_FILE" | cm_collapse_domains | sed 's/^/./' \
    | cm_write_file "$CM_SQUID_DIR/ai-deny.acl" 0640

  dom_count="$(grep -c . "$CM_SQUID_DIR/allow-domains.acl" || true)"
  ip_count="$(grep -c . "$CM_SQUID_DIR/allow-ips.acl" || true)"
  (( dom_count + ip_count > 0 )) || cm_die "The allowlist is empty — add sites first (cmanager add / edit $CM_WHITELIST_FILE)"
  # Squid rejects empty ACL files; keep a harmless placeholder.
  [[ -s "$CM_SQUID_DIR/ai-deny.acl" ]] || echo ".invalid" > "$CM_SQUID_DIR/ai-deny.acl"
  [[ -s "$CM_SQUID_DIR/allow-domains.acl" ]] || echo ".invalid" > "$CM_SQUID_DIR/allow-domains.acl"

  if (( sni )) && [[ ! -s "$CM_SQUID_DIR/tls.pem" ]]; then
    # Required by Squid for an ssl-bump port. It is never used to sign or
    # intercept anything: we only peek (read SNI) and splice or terminate.
    openssl req -x509 -newkey rsa:2048 -nodes -days 3650 -subj "/CN=contest-env peek-only" \
      -keyout "$CM_SQUID_DIR/tls.key" -out "$CM_SQUID_DIR/tls.crt" >/dev/null 2>&1 \
      || cm_die "openssl failed to create the proxy's placeholder certificate"
    cat "$CM_SQUID_DIR/tls.crt" "$CM_SQUID_DIR/tls.key" > "$CM_SQUID_DIR/tls.pem"
    rm -f "$CM_SQUID_DIR/tls.key" "$CM_SQUID_DIR/tls.crt"
    chmod 0640 "$CM_SQUID_DIR/tls.pem"
  fi

  {
    cat <<EOF
# Generated by contest-env ($(date '+%F %T')). Do not edit by hand:
# change $CM_WHITELIST_FILE and run 'sudo cmanager reload'.

EOF
    if (( sni )); then
      echo "http_port 127.0.0.1:${PROXY_PORT} ssl-bump tls-cert=$CM_SQUID_DIR/tls.pem generate-host-certificates=off"
    else
      echo "http_port 127.0.0.1:${PROXY_PORT}"
    fi
    cat <<EOF
pid_filename /run/contest-env-proxy/squid.pid
cache_effective_user proxy
cache deny all
cache_mem 8 MB
forwarded_for delete
httpd_suppress_version_string on
visible_hostname contest-proxy
shutdown_lifetime 2 seconds
client_persistent_connections on
pinger_enable off

logformat contest %ts.%03tu %>a %Ss/%03>Hs %rm %ru sni=%ssl::>sni
access_log stdio:$CM_PROXY_ACCESS_LOG logformat=contest
cache_log stdio:$CM_PROXY_LOG_DIR/cache.log
logfile_rotate 0

acl SSL_ports port 443
acl Safe_ports port 80 443
# A refused HTTPS tunnel gets a TCP reset rather than an error page (which
# the browser would show as a certificate warning).
acl refused_tunnel method CONNECT
deny_info TCP_RESET refused_tunnel
# -n: never reverse-resolve IP literals; names are matched as written.
acl ai_deny dstdomain -n "$CM_SQUID_DIR/ai-deny.acl"
acl allow_dom dstdomain -n "$CM_SQUID_DIR/allow-domains.acl"
acl ip_literal dstdom_regex -i ^[0-9.]+$ ^\[?[0-9a-f:]+\]?$
EOF
    if (( ip_count > 0 )); then echo "acl allow_ip dst \"$CM_SQUID_DIR/allow-ips.acl\""; fi
    cat <<'EOF'

# Order matters:
#  1. AI endpoints are refused even if an allowlist entry covers them.
#  2. Everything not allowlisted is refused BEFORE any DNS lookup.
#  3. Allowed names that resolve to loopback/link-local are refused (rebinding).
# Every refusal of a CONNECT ends in "refused_tunnel", so it is a TCP reset.
http_access deny ai_deny refused_tunnel
http_access deny ai_deny
http_access deny manager
EOF
    if (( ip_count > 0 )); then echo "http_access allow ip_literal allow_ip"; fi
    cat <<'EOF'
http_access deny !Safe_ports refused_tunnel
http_access deny !Safe_ports
http_access deny !SSL_ports refused_tunnel
http_access deny !allow_dom refused_tunnel
http_access deny !allow_dom
http_access deny to_localhost refused_tunnel
http_access deny to_localhost
http_access deny to_linklocal refused_tunnel
http_access deny to_linklocal
http_access allow allow_dom
http_access deny all
EOF

    if (( sni )); then
      cat <<EOF

# TLS: read the SNI, never decrypt. Splice allowed names, cut everything else.
acl step1 at_step SslBump1
acl ai_sni ssl::server_name "$CM_SQUID_DIR/ai-deny.acl"
acl allow_sni ssl::server_name "$CM_SQUID_DIR/allow-domains.acl"
ssl_bump peek step1
ssl_bump terminate ai_sni
ssl_bump splice allow_sni
EOF
      if (( ip_count > 0 )); then echo "ssl_bump splice ip_literal allow_ip"; fi
      echo "ssl_bump terminate all"
    fi
  } | cm_write_file "$CM_SQUID_CONF" 0640
  chgrp "$proxy_group" "$CM_SQUID_DIR"/* 2>/dev/null || true

  local sq; sq="$(cm_squid_bin)" || cm_die "Squid is not installed — run 'sudo cmanager setup'"
  "$sq" -k parse -f "$CM_SQUID_CONF" >/dev/null 2>&1 \
    || { "$sq" -k parse -f "$CM_SQUID_CONF" 2>&1 | grep -iE 'error|fatal' | head -5 >&2
         cm_die "Generated proxy configuration is invalid ($CM_SQUID_CONF)"; }

  if (( sni )); then
    cm_ok "Proxy config: $dom_count domain rule(s), $ip_count IP rule(s), SNI enforcement ON"
  else
    cm_warn "Proxy config: SNI enforcement OFF (Squid without OpenSSL). Install 'squid-openssl' for full protection."
  fi
}

cm_proxy_start() {
  # The distribution's own squid.service would fight for the port; we never use it.
  if systemctl is-enabled --quiet squid.service 2>/dev/null || systemctl is-active --quiet squid.service 2>/dev/null; then
    systemctl disable --now squid.service >/dev/null 2>&1 || true
  fi
  systemctl daemon-reload
  systemctl enable "$CM_PROXY_UNIT" >/dev/null 2>&1
  systemctl restart "$CM_PROXY_UNIT" || { journalctl -u "$CM_PROXY_UNIT" -n 20 --no-pager >&2 || true
                                          cm_die "The contest proxy failed to start"; }
  cm_ok "Proxy listening on 127.0.0.1:${PROXY_PORT}"
}

# Hot reload after an allowlist edit (no dropped connections for allowed sites).
cm_proxy_reload() {
  cm_proxy_render
  if systemctl is-active --quiet "$CM_PROXY_UNIT"; then
    systemctl reload "$CM_PROXY_UNIT"
    cm_ok "Proxy reloaded"
  fi
}

cm_proxy_stop() {
  systemctl disable --now "$CM_PROXY_UNIT" >/dev/null 2>&1 || true
}

cm_proxy_active() { systemctl is-active --quiet "$CM_PROXY_UNIT"; }

# Show hosts the proxy refused recently: "count  host  [reason]".
#   TCP_DENIED ............ not on the allowlist (or on the AI denylist)
#   NONE_NONE/200 + SNI ≠ CONNECT host ... TLS name mismatch (fronting attempt)
cm_proxy_denied() {
  local lines="${1:-5000}"
  [[ -r "$CM_PROXY_ACCESS_LOG" ]] || { cm_warn "No proxy log yet ($CM_PROXY_ACCESS_LOG)"; return 0; }
  tail -n "$lines" "$CM_PROXY_ACCESS_LOG" | awk '
    {
      host = $5; sub(/^[a-z]+:\/\//, "", host); sub(/\/.*/, "", host); sub(/:[0-9]+$/, "", host)
      sni = ""; if (match($0, /sni=[^ ]+/)) sni = substr($0, RSTART + 4, RLENGTH - 4)
      if ($3 ~ /^TCP_DENIED\//)                        n[host "  (not allowed)"]++
      else if ($3 == "NONE_NONE/200" && $4 == "CONNECT" && sni != "-" && sni != "" && sni != host)
                                                        n[sni "  (TLS name mismatch via " host ")"]++
    }
    END { for (h in n) printf "%6d  %s\n", n[h], h }' | sort -rn
}
